source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.1'

target 'DopeSquad' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "MapleBacon"

  target 'DopeSquadTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
